// 가방 요약용 문구입니다. 실제 효과·가격·대상 규칙은 공유 아이템 정의를 사용합니다.
export const ITEM_FLAVORS=Object.freeze({
  'star-sticker':'손끝에 작은 별빛이 내려앉아요.',
  'space-snack':'한 입에 은하수의 달콤함을 담았어요.',
  'asteroid-helmet':'작은 별의 단단한 마음을 썼어요.',
  'firefly-lamp':'어둠 속에 반딧불이 숨 쉬어요.',
  'rainbow-tail':'걸음마다 무지갯빛 꿈이 따라와요.',
  'mini-satellite':'내 곁을 도는 작은 별 친구예요.',
  'starlight-cape':'밤하늘의 반짝임을 두른 망토예요.',
  'meteor-board':'별똥별의 긴 꼬리를 타고 달려요.',
  'space-food-card':'먼 여행에 온기를 더하는 한 끼예요.',
  'space-robot-card':'작은 기계 심장에 다정함을 담았어요.',
  'alien-card':'낯선 별에서 온 호기심 많은 친구예요.',
  'space-suit-card':'별 사이를 거니는 여행자의 옷이에요.',
  'meteor-fragment-card':'긴 우주 여행의 흔적을 품었어요.',
  'little-sun-card':'손바닥 위에 작은 햇살이 피어요.',
  'little-moon-card':'작은 달빛이 조용히 미소 지어요.',
  'moon-rabbit-card':'달빛 풀밭을 폴짝이는 친구예요.',
  'asteroid-card':'우주를 떠도는 작은 돌의 꿈이에요.',
  'spaceship-card':'새로운 별을 향해 돛을 올려요.',
  'satellite-card':'먼 하늘에서 별들의 안부를 전해요.',
  'galaxy-card':'수많은 별이 흐르는 빛의 강이에요.',
  'spaceman-card':'별 너머를 꿈꾸는 용감한 여행자예요.',
  'sun-rabbit-card':'햇살 사이를 폴짝이는 친구예요.',
  'alien-rabbit-card':'낯선 별에서도 토끼는 꿈을 꿔요.',
  'android-card':'반짝이는 눈에 작은 마음을 담았어요.',
  'sun-card':'따스한 햇빛을 품은 별이에요.',
  'moon-card':'서늘한 달빛을 품은 별이에요.',
  'space-station-card':'별을 여행하는 이들의 작은 쉼터예요.',
  'great-spaceship-card':'커다란 꿈을 싣고 우주를 건너요.',
  'supernova-alpha-card':'별의 마지막 숨결이 환하게 피어요.',
  'supernova-beta-card':'먼 우주에 새로운 빛이 번져요.',
  'galaxy-cluster-card':'은하들이 모여 빛의 마을을 이뤄요.',
  'rabbit-princess-card':'달빛 왕관을 쓴 다정한 공주예요.',
  'comet-card':'밤하늘에 긴 빛의 편지를 남겨요.',
  'alien-creature-card':'신비로운 눈빛에 우주를 담았어요.',
  'solar-system-card':'해를 중심으로 별의 춤이 이어져요.',
  'black-hole-card':'깊은 어둠 속에 우주의 비밀이 있어요.',
  'nebula-card':'별이 태어나는 포근한 빛의 구름이에요.',
  'betelgeuse-card':'붉은 별빛이 먼 하늘을 물들여요.',
  'total-eclipse-card':'잠시 고요해진 해가 빛의 고리를 남겨요.',
  'supercluster-card':'셀 수 없는 은하가 한 꿈을 꾸어요.',
  'alien-queen-card':'먼 별의 왕관에 신비가 깃들었어요.',
  'gold-new-life-card':'낯선 땅에 새로운 꿈이 싹터요.',
  'gold-comet-card':'스쳐 간 별빛의 여운을 담았어요.',
  'gold-rest-card':'고요한 밤에 별도 잠시 쉬어 가요.',
  'gold-alien-encounter-card':'낯선 눈빛과 반가운 인사를 나눠요.',
  'gold-space-food-card':'별 사이의 식탁에 온기가 피어요.',
  'gold-polaris-card':'밤하늘 한자리를 지키는 빛이에요.',
  'gold-black-hole-card':'어둠의 가장자리에 금빛이 맴돌아요.',
  'gold-sunlight-card':'금빛 햇살이 마음에 내려앉아요.',
  'gold-big-bang-card':'우주의 첫 빛이 힘차게 깨어나요.',
  'gold-launch-card':'설레는 마음을 싣고 하늘로 떠나요.',
  'gold-event-horizon-card':'빛과 어둠이 맞닿은 경계예요.',
  'gold-moon-life-card':'고요한 달에도 작은 꿈이 살아요.',
  'gold-sun-and-moon-card':'낮과 밤의 빛이 나란히 머물러요.',
  'gold-wormhole-card':'별과 별 사이에 비밀 길이 열려요.',
  'gold-asteroid-collision-card':'별의 만남이 눈부신 불꽃을 남겨요.',
  'gold-our-galaxy-card':'우리가 사는 별의 마을이에요.',
  'gold-zodiac-card':'열두 별자리가 하늘을 수놓아요.',
  'gold-light-speed-card':'한 줄기 빛이 우주를 가로질러요.',
  'gold-mercury-card':'해 곁을 맴도는 작은 여행자예요.',
  'gold-venus-card':'새벽과 저녁을 밝히는 보석이에요.',
  'gold-earth-card':'푸른 바다에 우리의 꿈이 살아요.',
  'gold-mars-card':'붉은 모래 위에 모험이 기다려요.',
  'gold-jupiter-card':'거대한 구름에 소용돌이가 춤춰요.',
  'gold-saturn-card':'고운 고리를 두른 하늘의 보석이에요.',
  'gold-uranus-card':'연푸른 빛으로 조용히 돌아요.',
  'gold-neptune-card':'먼 우주의 푸른 바람을 품었어요.',
  'gold-pluto-card':'아득한 곳에서 작은 빛이 반겨요.',
  'gold-planet-exploration-card':'발걸음마다 새로운 별을 만나요.',
  'gold-cosmic-evolution-card':'오랜 시간 속에 우주가 자라나요.',
  'gold-telescope-card':'작은 창으로 먼 별의 꿈을 바라봐요.',
  'star-card':'아직 펼치지 않은 별의 이야기를 담았어요.'
});

export const itemFlavor=item=>ITEM_FLAVORS[item.id]||'작은 빛에 우주의 꿈을 담았어요.';
