import test from 'node:test';
import assert from 'node:assert/strict';
import {createAudio} from '../client/audio.js';

test('제공된 파일 배경음악은 맵마다 반복하고 태양 낙원 1·2가 재생 위치를 공유한다',async()=>{
  const players=new Map(),storage={getItem:()=>null,setItem:()=>{}};
  const audio=createAudio({storage,mediaFactory:(id,url)=>{
    const media={src:url,paused:true,currentTime:0,volume:1,muted:false,loop:false,playCount:0,
      async play(){this.paused=false;this.playCount++;},pause(){this.paused=true;}};
    players.set(id,media);return media;
  }});
  try{
    assert.equal(await audio.playBgm('lobby'),true);
    const lobby=players.get('lobby');
    assert.equal(lobby.src,'/assets/audio/login-in-front-of-love.mp3');
    assert.equal(lobby.loop,true);assert.equal(lobby.paused,false);
    lobby.currentTime=10;
    assert.equal(await audio.playBgm('star-street'),true);
    const shelter=players.get('star-street');
    assert.equal(lobby.paused,true);assert.equal(lobby.currentTime,0);
    assert.equal(shelter.src,'/assets/audio/star-street-pposong.mp3');
    assert.equal(shelter.loop,true);assert.equal(shelter.paused,false);
    assert.equal(await audio.playBgm('milky-valley'),true);
    const valley=players.get('milky-valley');
    assert.equal(shelter.paused,true);
    assert.equal(valley.src,'/assets/audio/milky-valley-silent-morning.mp3');
    assert.equal(valley.loop,true);assert.equal(valley.paused,false);
    assert.equal(await audio.playBgm('space-plaza'),true);
    const plaza=players.get('space-plaza');
    assert.equal(valley.paused,true);
    assert.equal(plaza.src,'/assets/audio/space-plaza-my-captain.mp3');
    assert.equal(plaza.loop,true);assert.equal(plaza.paused,false);
    assert.equal(await audio.playBgm('moon-garden'),true);
    const crossroads=players.get('moon-garden');
    assert.equal(plaza.paused,true);
    assert.equal(crossroads.src,'/assets/audio/moon-garden-picnic.mp3');
    assert.equal(crossroads.loop,true);assert.equal(crossroads.paused,false);
    assert.equal(await audio.playBgm('sun-paradise'),true);
    const sun=players.get('sun-paradise');
    assert.equal(crossroads.paused,true);
    assert.equal(sun.src,'/assets/audio/sun-paradise-school-road.mp3');
    sun.currentTime=37;
    assert.equal(await audio.playBgm('sun-paradise-2'),true);
    assert.equal(players.has('sun-paradise-2'),false);
    assert.equal(sun.paused,false);assert.equal(sun.currentTime,37);assert.equal(sun.playCount,1);
    assert.equal(await audio.playBgm('sun-paradise'),true);
    assert.equal(sun.paused,false);assert.equal(sun.currentTime,37);assert.equal(sun.playCount,1);
    audio.setVolume(.6);audio.setMuted(true);
    assert.equal(lobby.volume,.6);assert.equal(shelter.volume,.6);assert.equal(valley.volume,.6);assert.equal(plaza.volume,.6);assert.equal(crossroads.volume,.6);assert.equal(sun.volume,.6);
    assert.equal(lobby.muted,true);assert.equal(shelter.muted,true);assert.equal(valley.muted,true);assert.equal(plaza.muted,true);assert.equal(crossroads.muted,true);assert.equal(sun.muted,true);
    audio.setMuted(false);assert.equal(sun.muted,false);
    assert.equal(await audio.playBgm('sun-paradise-3'),true);
    assert.equal(sun.paused,true);assert.equal(sun.currentTime,0);
    const battle=players.get('sun-paradise-3');
    assert.equal(battle.src,'/assets/audio/sun-paradise-3-last-battle.mp3');
    assert.equal(battle.loop,true);assert.equal(battle.paused,false);
    assert.equal(await audio.playBgm('moon-paradise-3'),true);
    const moon=players.get('moon-paradise-3');
    assert.equal(battle.paused,true);assert.equal(moon.src,'/assets/audio/moon-paradise-3-ancient-kingdom.mp3');
    assert.equal(moon.loop,true);assert.equal(moon.paused,false);
    assert.equal(await audio.playBgm('planet:dept-a'),true);
    const interior=players.get('planet:dept-a');
    assert.equal(moon.paused,true);assert.equal(interior.src,'/assets/audio/planet-interior-waddle.mp3');
    assert.equal(interior.loop,true);assert.equal(interior.paused,false);
    interior.currentTime=12;
    assert.equal(await audio.playBgm('planet:dept-b'),true);
    assert.equal(players.has('planet:dept-b'),false);assert.equal(interior.currentTime,12);
    audio.setVolume(.42);audio.setMuted(true);
    assert.equal(battle.volume,.42);assert.equal(moon.volume,.42);assert.equal(interior.volume,.42);
    assert.equal(battle.muted,true);assert.equal(moon.muted,true);assert.equal(interior.muted,true);
    assert.equal(await audio.playBgm('lobby'),true);
    assert.equal(lobby.paused,false);assert.equal(shelter.paused,true);assert.equal(valley.paused,true);assert.equal(plaza.paused,true);assert.equal(crossroads.paused,true);assert.equal(sun.paused,true);assert.equal(interior.paused,true);
    audio.stopBgm();assert.equal(lobby.paused,true);
  }finally{audio.dispose();}
});
