import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { io } from 'socket.io-client';
import { createClassroomServer } from '../server/app.js';
import { addPlanet } from '../server/world.js';
import {weeklyRewards} from '../server/temple.js';
import { INTERIOR, MAP, PLANET_COLORS, PLAZA_ID, interiorIdOf } from '../shared/config.js';

const key = 'department-test-private-not-real-key';
const call = (socket, event, data = {}) => socket.timeout(3000).emitWithAck(event, data);
const reportBoard = INTERIOR.objects.find(object => object.kind === 'report-board');

test('department realtime access, work, distribution, privacy, and persistence', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'department-realtime-'));
  const sockets = [];
  let game = createClassroomServer({ teacherKey: key, dataDir: dir, studentHours: false });
  t.after(async () => { for (const socket of sockets) socket.disconnect(); if (game) await game.close(); await rm(dir, { recursive: true, force: true }); });
  let address = await game.listen();
  const connect = async () => {
    const socket = io(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], forceNew: true, reconnection: false });
    sockets.push(socket);
    await new Promise((resolve, reject) => { socket.once('connect', resolve); socket.once('connect_error', reject); });
    return socket;
  };
  const teacher = await connect();
  const first = await connect();
  const second = await connect();
  const outsider = await connect();
  const created = await call(teacher, 'room:create', { teacherKey: key, title: '부서 실시간 검사', allowedNames: ['1', '2', '3'] });
  assert.equal(created.ok, true);
  const joins = [];
  joins.push(await call(first, 'room:join', { code: created.room.code, nickname: '1', pin: created.credentials.find(c => c.nickname === '1').pin }));
  joins.push(await call(second, 'room:join', { code: created.room.code, nickname: '2', pin: created.credentials.find(c => c.nickname === '2').pin }));
  assert.equal((await call(outsider,'room:join',{code:created.room.code,nickname:'3',pin:created.credentials.find(c=>c.nickname==='3').pin})).ok,true);
  assert.ok(joins.every(result => result.ok));

  let room = game.store.rooms.get(created.room.code);
  let teacherPlayer = room.players.get(created.selfId);
  let firstPlayer = room.players.get(joins[0].selfId);
  let secondPlayer = room.players.get(joins[1].selfId);
  let planet;
  game.store.transact(() => {
    planet = addPlanet(room, { name: '실적행성', description: '', x: 190, y: 175, color: PLANET_COLORS[0], rules: ['협력해요'], createdBy: teacherPlayer.id, templateId: 'reading' });
    for (const player of [firstPlayer, secondPlayer]) player.avatar.departmentId = planet.id;
  });
  const refresh = () => {
    room = game.store.rooms.get(created.room.code);
    teacherPlayer = room.players.get(created.selfId);
    firstPlayer = room.players.get(joins[0].selfId);
    secondPlayer = room.players.get(joins[1].selfId);
    planet = room.planets.get(planet.id);
  };
  const insideNearBoard = player => Object.assign(player, { mapId: interiorIdOf(planet.id), x: reportBoard.x, y: reportBoard.y });
  const plazaNearPlanet = player => Object.assign(player, { mapId: PLAZA_ID, x: planet.x + planet.radius + 10, y: planet.y });
  plazaNearPlanet(teacherPlayer);
  await call(teacher, 'department:get', { planetId: planet.id });
  const snapshot = game.store.snapshot(room, room.players.get(firstPlayer.id));
  assert.equal(snapshot.planets.find(p => p.id === planet.id).reportPending, false);
  assert.equal(JSON.stringify(snapshot).includes('treasury'), false);
  assert.equal(Object.hasOwn(snapshot.planets.find(p => p.id === planet.id), 'work'), false);

  assert.equal((await call(outsider, 'department:get', { planetId: planet.id })).ok, false);
  assert.equal((await call(first, 'department:get', { planetId: planet.id })).ok, false);
  refresh();
  insideNearBoard(firstPlayer);
  assert.equal((await call(first, 'department:save', { planetId: planet.id, text: '첫 보고서', version: 0 })).ok, true);
  refresh();
  assert.equal((await call(first, 'department:submit', { planetId: planet.id, text: '완성된 보고서', version: 1 })).ok, true);
  refresh();
  assert.equal((await call(first, 'department:submit', { planetId: planet.id, text: '중복 제출', version: 2 })).ok, false);
  assert.equal((await call(second, 'department:award', { planetId: planet.id, amount: 7, version: 2 })).ok, false);
  assert.equal((await call(teacher, 'department:award', { planetId: planet.id, amount: 7, version: 2 })).ok, true);
  refresh();
  assert.equal(planet.work.balance, 7);
  assert.equal(planet.work.report.status, 'draft');

  insideNearBoard(firstPlayer);
  assert.equal((await call(first, 'department:propose', { planetId: planet.id, allocations: [{ playerId: firstPlayer.id, quantity: 0 }, { playerId: secondPlayer.id, quantity: 7 }] })).ok, true);
  refresh();
  const proposalId = planet.work.distribution.id;
  assert.equal((await call(outsider, 'department:confirm', { planetId: planet.id, proposalId })).ok, false);
  assert.equal((await call(first, 'department:confirm', { planetId: planet.id, proposalId })).completed, false);
  refresh();
  assert.equal(planet.work.distribution.confirmedIds.length, 1);
  const balanceBeforeDeniedLeave = planet.work.balance;

  for (const socket of sockets) socket.disconnect();
  await game.close();
  game = createClassroomServer({ teacherKey: key, dataDir: dir, studentHours: false });
  address = await game.listen();
  const resumed = io(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], forceNew: true, reconnection: false });
  sockets.push(resumed);
  await new Promise((resolve, reject) => { resumed.once('connect', resolve); resumed.once('connect_error', reject); });
  const resumedJoin = await call(resumed, 'room:join', { code: created.room.code, nickname: '1', pin: created.credentials.find(c => c.nickname === '1').pin });
  assert.equal(resumedJoin.selfId, firstPlayer.id);
  room = game.store.rooms.get(created.room.code); planet = room.planets.get(planet.id);
  assert.equal(planet.work.report.status, 'draft');
  assert.equal(planet.work.distribution.confirmedIds.length, 1);
  assert.equal(planet.work.balance, balanceBeforeDeniedLeave);
  const restoredFirst = room.players.get(firstPlayer.id);
  const restoredSecond = room.players.get(secondPlayer.id);
  Object.assign(restoredFirst, { mapId: interiorIdOf(planet.id), x: reportBoard.x, y: reportBoard.y });
  assert.equal((await call(resumed, 'department:confirm', { planetId: planet.id, proposalId })).completed, false);
  const resumedSecond = io(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], forceNew: true, reconnection: false });
  sockets.push(resumedSecond);
  await new Promise((resolve, reject) => { resumedSecond.once('connect', resolve); resumedSecond.once('connect_error', reject); });
  const secondJoin = await call(resumedSecond, 'room:join', { code: created.room.code, nickname: '2', pin: created.credentials.find(c => c.nickname === '2').pin });
  assert.equal(secondJoin.selfId, restoredSecond.id);
  room = game.store.rooms.get(created.room.code); planet = room.planets.get(planet.id);
  Object.assign(room.players.get(restoredSecond.id), { mapId: interiorIdOf(planet.id), x: reportBoard.x, y: reportBoard.y });
  const completed = await call(resumedSecond, 'department:confirm', { planetId: planet.id, proposalId });
  assert.equal(completed.completed, true);
  refresh();
  assert.equal(planet.work.distribution, null);
  assert.equal(planet.work.balance, 0);
  assert.equal(planet.work.history.length, 1);
  assert.equal(room.players.get(secondPlayer.id).starShards, 7);
  assert.equal(room.players.get(firstPlayer.id).starShards, 0);
  assert.equal(weeklyRewards(room).rows.find(row=>row.playerId===secondPlayer.id).total,7);
  assert.equal(weeklyRewards(room).rows.find(row=>row.playerId===firstPlayer.id).total,0);
  const duplicate=await call(resumedSecond,'department:confirm',{planetId:planet.id,proposalId});
  assert.equal(duplicate.ok,false);refresh();assert.equal(secondPlayer.starShards,7);
  game.store.transact(()=>{planet.work.balance=5;});
  assert.equal((await call(resumed,'department:propose',{planetId:planet.id,allocations:[{playerId:firstPlayer.id,quantity:0},{playerId:secondPlayer.id,quantity:5}]})).ok,true);
  assert.equal((await call(resumed, 'planet:leave', { planetId: planet.id })).ok, true);
  refresh();
  assert.equal(planet.work.balance, 5);
  assert.equal(planet.work.distribution,null);
  assert.equal(restoredFirst.starShards, 0);
  assert.equal(restoredSecond.starShards, 7);
});
