import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {io} from 'socket.io-client';
import {createClassroomServer} from '../server/app.js';
import {addPlanet} from '../server/world.js';
import {INTERIOR,interiorIdOf} from '../shared/config.js';
import {INTERIOR_DECOR_COLORS,INTERIOR_DECOR_OBJECTS,INTERIOR_DECOR_TARGETS} from '../shared/interior-decor.js';
import {validateInteriorDecor} from '../server/interior-decor.js';

test('부서 내부 다섯 오브젝트에는 기본색 포함 7색과 각각 3가지 모양이 있다',()=>{
  assert.equal(INTERIOR_DECOR_COLORS.length,7);
  assert.deepEqual(INTERIOR_DECOR_TARGETS,['room','mailbox','board','report-board','warning-rock']);
  assert.deepEqual(INTERIOR_DECOR_OBJECTS.map(object=>object.id),['room','mailbox','board','report-board','warning-rock','door']);
  assert.deepEqual(INTERIOR_DECOR_OBJECTS.find(object=>object.id==='room').shapes.map(shape=>shape.name),['은빛 석판','별무늬 석판','은빛 격자']);
  assert.deepEqual(INTERIOR_DECOR_OBJECTS.find(object=>object.id==='mailbox').shapes.map(shape=>shape.name),['우체통','별 장식','달 장식']);
  assert.equal(INTERIOR_DECOR_OBJECTS.find(object=>object.id==='report-board').name,'실적작성표');
  const machine=INTERIOR.objects.find(object=>object.id==='department-control-machine');
  assert.deepEqual([machine.name,machine.kind,machine.x,machine.y],['부서행성 제어장치','interior-decor-machine',960,590]);
  for(const object of INTERIOR_DECOR_OBJECTS)assert.equal(object.shapes.length,3);
  assert.deepEqual(validateInteriorDecor(),{});
  assert.deepEqual(validateInteriorDecor({door:{colorId:'rose',shapeId:'portal'}}),{door:{colorId:'rose',shapeId:'portal'}});
  assert.throws(()=>validateInteriorDecor({'warning-rock':{colorId:'neon',shapeId:'default'}}),/꾸미기 저장/);
  assert.throws(()=>validateInteriorDecor({'warning-rock':{colorId:'rose',shapeId:'unlisted'}}),/꾸미기 저장/);
  assert.throws(()=>validateInteriorDecor({'not-an-object':{colorId:'rose',shapeId:'default'}}),/꾸미기 저장/);
});

test('소속 학생만 가까운 오브젝트를 꾸미고 행성별 선택은 재시작 뒤에도 남는다',async t=>{
  const directory=await mkdtemp(join(tmpdir(),'interior-decor-')),key='decor-persistence-test-key',sockets=[];
  let game=createClassroomServer({teacherKey:key,dataDir:directory,studentHours:false}),address=await game.listen();
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();await rm(directory,{recursive:true,force:true});});
  const connect=async()=>{const socket=io('http://127.0.0.1:'+address.port,{transports:['websocket'],reconnection:false});sockets.push(socket);await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  const call=(socket,event,data={})=>socket.timeout(3000).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:key,allowedNames:['1','2']});
  const pin=name=>created.credentials.find(credential=>credential.nickname===name).pin;
  const memberSocket=await connect(),memberJoin=await call(memberSocket,'room:join',{code:created.room.code,nickname:'1',pin:pin('1')});
  const outsiderSocket=await connect(),outsiderJoin=await call(outsiderSocket,'room:join',{code:created.room.code,nickname:'2',pin:pin('2')});
  let room=game.store.rooms.get(created.room.code),member=room.players.get(memberJoin.selfId),outsider=room.players.get(outsiderJoin.selfId);
  const planet=addPlanet(room,{name:'예술행성',description:'',x:360,y:430,color:'#c5c9f7',rules:['함께 꾸며요'],templateId:'art'});
  const other=addPlanet(room,{name:'독서행성',description:'',x:1150,y:430,color:'#d1a7f2',rules:['책을 읽어요'],templateId:'reading'});
  const refresh=()=>{room=game.store.rooms.get(created.room.code);member=room.players.get(memberJoin.selfId);outsider=room.players.get(outsiderJoin.selfId);return room.planets.get(planet.id);};
  const position=(playerId,x,y)=>{refresh();Object.assign(room.players.get(playerId),{x,y});};
  member.avatar.departmentId=planet.id;
  const event='planet:interior-decor:set',object=INTERIOR.objects.find(item=>item.id==='warning-rock');
  const machine=INTERIOR.objects.find(item=>item.id==='department-control-machine');
  Object.assign(member,{mapId:interiorIdOf(planet.id),x:machine.x,y:machine.y});
  Object.assign(outsider,{mapId:interiorIdOf(planet.id),x:machine.x,y:machine.y});
  const selected={planetId:planet.id,objectId:object.id,colorId:'mint',shapeId:'crystal',controlId:'department-control-machine'};
  assert.equal((await call(outsiderSocket,event,selected)).ok,false);
  assert.equal((await call(memberSocket,event,{...selected,colorId:'invalid'})).ok,false);
  assert.equal((await call(memberSocket,event,{...selected,shapeId:'invalid'})).ok,false);
  assert.deepEqual(refresh().interiorDecor,{});
  position(memberJoin.selfId,600,540);assert.equal((await call(memberSocket,event,selected)).ok,false);
  position(memberJoin.selfId,object.x,object.y+70);
  assert.equal((await call(memberSocket,event,{...selected,controlId:undefined})).ok,false,'대상 바로 옆이어도 controlId 없이는 꾸밀 수 없어야 합니다.');
  assert.equal((await call(memberSocket,event,{...selected,objectId:'door'})).ok,false);
  position(memberJoin.selfId,machine.x,machine.y);
  const response=await call(memberSocket,event,selected);assert.equal(response.ok,true,response.error);
  assert.deepEqual(refresh().interiorDecor['warning-rock'],{colorId:'mint',shapeId:'crystal'});
  assert.deepEqual(game.store.snapshot(room,outsider).planets.find(item=>item.id===planet.id).interiorDecor['warning-rock'],{colorId:'mint',shapeId:'crystal'});
  const controlStyle={planetId:planet.id,objectId:'board',controlId:machine.id,colorId:'sky',shapeId:'tablet'};
  position(memberJoin.selfId,machine.x,machine.y);position(outsiderJoin.selfId,machine.x,machine.y);
  assert.equal((await call(outsiderSocket,event,controlStyle)).ok,false,'타 부서 학생은 제어장치로 꾸밀 수 없어야 합니다.');
  assert.equal((await call(memberSocket,event,controlStyle)).ok,true,'소속 학생은 제어장치 근처에서 떨어진 게시판도 꾸밀 수 있어야 합니다.');
  assert.deepEqual(refresh().interiorDecor.board,{colorId:'sky',shapeId:'tablet'});
  for(const id of INTERIOR_DECOR_TARGETS.filter(id=>id!=='warning-rock'&&id!=='board')){
    const definition=INTERIOR_DECOR_OBJECTS.find(item=>item.id===id);
    const shapeId=definition.shapes[1].id;
    assert.equal((await call(memberSocket,event,{...controlStyle,objectId:id,shapeId,colorId:id==='room'?'mint':'sky'})).ok,true,`${id} 제어장치 꾸미기`);
  }
  assert.equal((await call(memberSocket,event,{...controlStyle,objectId:'door'})).ok,false,'이전 저장 호환 문은 새 꾸미기 대상에서 제외합니다.');
  assert.equal((await call(memberSocket,event,{...controlStyle,controlId:'forged'})).ok,false,'위조 controlId를 거부합니다.');
  position(memberJoin.selfId,machine.x+300,machine.y+100);
  assert.equal((await call(memberSocket,event,{...controlStyle,colorId:'rose'})).ok,false,'제어장치와 대상 둘 다 멀면 저장을 막아야 합니다.');
  assert.deepEqual(other.interiorDecor,{});
  for(const socket of sockets)socket.disconnect();await game.close();
  game=createClassroomServer({teacherKey:key,dataDir:directory,studentHours:false});address=await game.listen();
  const reopenedTeacher=await connect();assert.equal((await call(reopenedTeacher,'room:open',{teacherKey:key,code:created.room.code})).ok,true);
  room=game.store.rooms.get(created.room.code);
  assert.deepEqual(room.planets.get(planet.id).interiorDecor['warning-rock'],{colorId:'mint',shapeId:'crystal'});
  assert.deepEqual(room.planets.get(planet.id).interiorDecor.board,{colorId:'sky',shapeId:'tablet'});
  assert.deepEqual(room.planets.get(planet.id).interiorDecor.room,{colorId:'mint',shapeId:'star'});
  assert.deepEqual(room.planets.get(planet.id).interiorDecor.mailbox,{colorId:'sky',shapeId:'star'});
  assert.deepEqual(room.planets.get(other.id).interiorDecor,{});
});
