import test from 'node:test';
import assert from 'node:assert/strict';
import {io} from 'socket.io-client';
import {createClassroomServer} from '../server/app.js';
import {toRecord,fromRecord,pinHash} from '../server/persistent-rooms.js';
import {MAP,STREET,SHARDS} from '../shared/config.js';
import {advanceMissions} from '../server/missions.js';
import {ENGLISH_WORDS} from '../shared/learning-questions.js';

test('게시판 미션은 학생 수락·교사 달성 확인·본인 완료 보상 순서로 한 번만 처리된다',async t=>{
  const key='mission-test-key',game=createClassroomServer({teacherKey:key,studentHours:false});
  const {port}=await game.listen(),url=`http://127.0.0.1:${port}`,sockets=[];
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();});
  const connect=async()=>{const socket=io(url,{transports:['websocket'],forceNew:true,reconnection:false});sockets.push(socket);
    await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  const call=(socket,event,data={})=>socket.timeout(3000).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:key,title:'미션',allowedNames:['1','2','3']});
  assert.equal(created.ok,true,created.error);
  const room=game.store.rooms.get(created.room.code),board=MAP.objects.find(o=>o.kind==='mission-board');
  const a=await connect(),joinedA=await call(a,'room:join',{code:room.code,nickname:'1'});
  const b=await connect(),joinedB=await call(b,'room:join',{code:room.code,nickname:'2'});
  for(const p of room.players.values())Object.assign(p,{mapId:MAP.id,x:board.x,y:board.y+board.radius+10});
  assert.equal((await call(a,'mission:create',{title:'학생의 가짜 미션',description:'가짜',rewardShards:1,distribution:'all'})).ok,false);
  const boardMission=await call(teacher,'mission:create',{title:'서로 돕기',description:'친구를 한 번 도와주고 선생님께 말씀드리기',rewardShards:2,distribution:'board'});
  assert.equal(boardMission.ok,true,boardMission.error);
  assert.equal(room.missions[0].acceptedIds.length,0);
  assert.equal((await call(a,'mission:claim',{missionId:boardMission.missionId})).ok,false);
  assert.equal((await call(a,'mission:accept',{missionId:boardMission.missionId})).ok,true);
  assert.equal((await call(a,'mission:accept',{missionId:boardMission.missionId})).ok,false);
  assert.equal((await call(a,'mission:claim',{missionId:boardMission.missionId})).ok,false);
  assert.equal((await call(a,'mission:confirm',{missionId:boardMission.missionId,studentId:joinedA.selfId})).ok,false);
  assert.equal((await call(teacher,'mission:confirm',{missionId:boardMission.missionId,studentId:joinedB.selfId})).ok,false);
  const confirmed=await call(teacher,'mission:confirm',{missionId:boardMission.missionId,studentId:joinedA.selfId});
  assert.equal(confirmed.ok,true,confirmed.error);
  assert.equal((await call(teacher,'mission:confirm',{missionId:boardMission.missionId,studentId:joinedA.selfId})).ok,false);
  const reward=await call(a,'mission:claim',{missionId:boardMission.missionId});
  assert.equal(reward.ok,true,reward.error);assert.equal(reward.rewardShards,2);
  assert.equal(room.players.get(joinedA.selfId).starShards,2);
  assert.equal((await call(a,'mission:claim',{missionId:boardMission.missionId})).ok,false);
  assert.equal((await call(b,'mission:claim',{missionId:boardMission.missionId})).ok,false);
  const view=game.store.snapshot(room,room.players.get(joinedA.selfId));
  assert.equal(view.missions[0].status,'claimed');assert.equal(JSON.stringify(view.missions).includes(joinedB.selfId),false);
  const all=await call(teacher,'mission:create',{title:'오늘의 약속',description:'약속 지키기',rewardShards:3,distribution:'all'});
  assert.equal(all.ok,true,all.error);
  assert.deepEqual(new Set(room.missions[1].acceptedIds),new Set([joinedA.selfId,joinedB.selfId]));
  const c=await connect(),joinedC=await call(c,'room:join',{code:room.code,nickname:'3'});
  assert.equal(joinedC.ok,true,joinedC.error);
  assert.ok(room.missions[1].acceptedIds.includes(joinedC.selfId));
  room.players.get(joinedC.selfId).pin=pinHash('1234');
  for(const p of room.players.values())if(p.role==='student'&&!p.pin)p.pin=pinHash('1234');
  const saved=toRecord(room);saved.createdAt=Date.now();
  const restored=fromRecord(saved);
  assert.equal(restored.missions[1].acceptedIds.length,3);
  assert.deepEqual(restored.missions[0].claimedIds,[joinedA.selfId]);
  room.players.get(joinedB.selfId).starShards=SHARDS.max;
  assert.equal((await call(teacher,'mission:confirm',{missionId:all.missionId,studentId:joinedB.selfId})).ok,true);
  assert.equal((await call(b,'mission:claim',{missionId:all.missionId})).ok,false);
  assert.equal(room.missions[1].claimedIds.includes(joinedB.selfId),false);
});

test('영어 발전소 자동미션은 서버 채점 10문제 중 7개 이상인 완료 판만 센다',async t=>{
  const key='english-mission-key',game=createClassroomServer({teacherKey:key,studentHours:false});
  const {port}=await game.listen(),url=`http://127.0.0.1:${port}`,sockets=[];
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();});
  const connect=async()=>{const socket=io(url,{transports:['websocket'],forceNew:true,reconnection:false});sockets.push(socket);
    await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  const call=(socket,event,data={})=>socket.timeout(3000).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:key,title:'영어 미션',allowedNames:['1']});
  assert.equal(created.ok,true,created.error);
  const room=game.store.rooms.get(created.room.code),studentSocket=await connect();
  const joined=await call(studentSocket,'room:join',{code:room.code,nickname:'1'});
  assert.equal(joined.ok,true,joined.error);
  const student=room.players.get(joined.selfId),station=STREET.objects.find(o=>o.kind==='english-station');
  Object.assign(student,{mapId:STREET.id,x:station.x,y:station.y+station.radius+5});
  const made=await call(teacher,'mission:auto:create',{title:'영어 별빛',description:'10문제 중 7문제 이상 성공 1회',rewardShards:3,distribution:'all',objective:'english-success',goal:1});
  assert.equal(made.ok,true,made.error);
  const meanings=new Map(ENGLISH_WORDS);
  async function play(correctCount){
    let question=await call(studentSocket,'learning:english:start');assert.equal(question.ok,true,question.error);
    for(let index=0;index<10;index++){
      const answer=meanings.get(question.prompt),selected=index<correctCount?answer:question.choices.find(choice=>choice!==answer);
      const result=await call(studentSocket,'learning:english:answer',{questionId:question.questionId,answer:selected});
      assert.equal(result.ok,true,result.error);assert.equal(result.right,index<correctCount);
      if(index===0)assert.equal((await call(studentSocket,'learning:english:answer',{questionId:question.questionId,answer:selected})).ok,false);
      if(index<9){question=await call(studentSocket,'learning:english:next');assert.equal(question.ok,true,question.error);}
      else return result;
    }
  }
  const failed=await play(6);assert.equal(failed.success,false);assert.equal(room.missions[0].completedIds.length,0);
  assert.equal((await call(studentSocket,'mission:claim',{missionId:made.missionId})).ok,false);
  const passed=await play(7);assert.equal(passed.success,true);assert.equal(room.missions[0].progress[student.id],1);
  assert.equal(student.starShards,0);
  const claimed=await call(studentSocket,'mission:claim',{missionId:made.missionId});assert.equal(claimed.ok,true,claimed.error);
  assert.equal(student.starShards,3);
});

test('자동미션은 서버에서 확인한 행동만 세고 학생이 완료 보상을 직접 받는다',async t=>{
  const key='auto-mission-key',game=createClassroomServer({teacherKey:key,studentHours:false});
  const {port}=await game.listen(),url=`http://127.0.0.1:${port}`,sockets=[];
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();});
  const connect=async()=>{const socket=io(url,{transports:['websocket'],forceNew:true,reconnection:false});sockets.push(socket);
    await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  const call=(socket,event,data={})=>socket.timeout(3000).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:key,title:'자동미션',allowedNames:['1']});
  assert.equal(created.ok,true,created.error);
  const room=game.store.rooms.get(created.room.code),studentSocket=await connect();
  const joined=await call(studentSocket,'room:join',{code:room.code,nickname:'1'});
  assert.equal(joined.ok,true,joined.error);
  const student=room.players.get(joined.selfId),gate=MAP.objects.find(o=>o.kind==='gate');
  assert.ok(gate);
  const made=await call(teacher,'mission:auto:create',{title:'우주 여행',description:'맵을 한 번 이동하기',rewardShards:2,distribution:'all',objective:'map-travel',goal:1});
  assert.equal(made.ok,true,made.error);
  assert.equal((await call(studentSocket,'mission:confirm',{missionId:made.missionId,studentId:student.id})).ok,false);
  assert.equal((await call(studentSocket,'mission:claim',{missionId:made.missionId})).ok,false);
  assert.equal((await call(teacher,'mission:confirm',{missionId:made.missionId,studentId:student.id})).ok,false);
  Object.assign(student,{mapId:MAP.id,x:gate.x,y:gate.y+gate.radius+5});
  const traveled=await call(studentSocket,'map:travel',{to:gate.target});assert.equal(traveled.ok,true,traveled.error);
  assert.equal(room.missions[0].progress[student.id],1);
  assert.equal(game.store.snapshot(room,student).missions[0].status,'ready');
  assert.equal(student.starShards,0);
  const claim=await call(studentSocket,'mission:claim',{missionId:made.missionId});assert.equal(claim.ok,true,claim.error);
  assert.equal(student.starShards,2);
  assert.equal((await call(studentSocket,'mission:claim',{missionId:made.missionId})).ok,false);
  assert.equal(advanceMissions(room,student,'map-travel'),false);
  student.pin=pinHash('1234');const saved=toRecord(room);saved.createdAt=Date.now();
  assert.equal(fromRecord(saved).missions[0].progress[student.id],1);
  assert.equal((await call(studentSocket,'mission:auto:create',{title:'속임수',description:'가짜',rewardShards:1,distribution:'all',objective:'map-travel',goal:1})).ok,false);
  assert.equal((await call(teacher,'mission:auto:create',{title:'잘못된 조건',description:'가짜',rewardShards:1,distribution:'all',objective:'fake',goal:1})).ok,false);
});
