import test from 'node:test';
import assert from 'node:assert/strict';
import { io } from 'socket.io-client';
import { createClassroomServer } from '../server/app.js';
import { RULES, PLANET, PLANET_COLORS, PLAZA_ID, interiorIdOf, MAP, STREET, STREET_ID, SHARDS, SHOP } from '../shared/config.js';
import { placementFree } from '../server/world.js';
const key='test-secret-not-for-deployment';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(t,options={}) {
 const game=createClassroomServer({teacherKey:key,...options}), address=await game.listen();
 const url='http://127.0.0.1:'+address.port,sockets=[];
 t.after(async()=>{for(const s of sockets)s.disconnect();await game.close();});
 async function connect(){
  const s=io(url,{transports:['websocket'],forceNew:true,reconnection:false});sockets.push(s);
  await new Promise((resolve,reject)=>{s.once('connect',resolve);s.once('connect_error',reject);});return s;
 }
 return {game,url,connect};
}
const call=(socket,event,data={})=>socket.timeout(3000).emitWithAck(event,data);
const create=s=>call(s,'room:create',{teacherKey:key,title:'테스트',allowedNames:Array.from({length:29},(_,i)=>String(i+1))});
test('real sockets enforce teacher permissions and keep rooms isolated',async t=>{
 const {connect,game}=await fixture(t),a=await connect(),b=await connect(),student=await connect();
 assert.equal((await call(student,'room:create',{teacherKey:'wrong',allowedNames:['1']})).ok,false);
 const ra=await create(a),rb=await create(b);assert.ok(ra.ok&&rb.ok);assert.notEqual(ra.room.code,rb.room.code);
 const joined=await call(student,'room:join',{code:ra.room.code,nickname:'1',role:'teacher',level:5});assert.ok(joined.ok);
 assert.equal(joined.room.players.find(p=>p.id===joined.selfId).role,'student');
 assert.equal((await call(student,'room:close')).ok,false);
 let leak=false;b.on('room:state',r=>{if(r.code===ra.room.code)leak=true;});
 const states=[];a.on('world:positions',p=>states.push(p));
 const p=game.store.rooms.get(ra.room.code).players.get(joined.selfId),x=p.x;
 student.emit('player:input',{x:1,y:0});await sleep(240);
 assert.ok(p.x>x);assert.ok(states.some(s=>s.positions.some(v=>v[0]===joined.selfId)));
 student.emit('player:input',{x:Infinity,y:0});student.emit('player:input',{x:99999,y:0});
 student.emit('player:input',{x:0,y:0});await sleep(70);const stopped=p.x;await sleep(200);assert.equal(p.x,stopped);
 assert.equal(leak,false);assert.equal(game.store.rooms.get(rb.room.code).players.size,1);
});
test('30 real browser-equivalent connections admitted, extra and duplicate membership rejected',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const students=await Promise.all(Array.from({length:29},()=>connect()));
 const joins=await Promise.all(students.map((s,i)=>call(s,'room:join',{code:r.room.code,nickname:String(i+1)})));
 assert.ok(joins.every(r=>r.ok));assert.equal(game.store.rooms.get(r.room.code).players.size,30);
 assert.equal((await call(await connect(),'room:join',{code:r.room.code,nickname:'30'})).ok,false);
 assert.equal((await call(students[0],'room:join',{code:r.room.code,nickname:'2'})).ok,false);
});
test('disconnect, authenticated resume, expiry and explicit teacher closure',async t=>{
 const {connect,game}=await fixture(t,{reconnectMs:500}),teacher=await connect(),r=await create(teacher);
 const student=await connect(),joined=await call(student,'room:join',{code:r.room.code,nickname:'1'});
 student.disconnect();await sleep(70);const resumed=await connect();
 const result=await call(resumed,'session:resume',{token:joined.token});assert.ok(result.ok);assert.equal(result.selfId,joined.selfId);
 assert.equal((await call(await connect(),'session:resume',{token:joined.token})).ok,false);
 resumed.disconnect();await sleep(650);
 assert.equal((await call(await connect(),'session:resume',{token:joined.token})).ok,false);
 const newStudent=await connect();assert.ok((await call(newStudent,'room:join',{code:r.room.code,nickname:'1'})).ok);
 const closed=new Promise(resolve=>newStudent.once('room:closed',resolve));
 assert.ok((await call(teacher,'room:leave')).ok);await closed;assert.equal(game.store.rooms.size,0);assert.equal(game.store.sessions.size,0);
});
test('teacher disconnect pauses movement and expiry closes the room',async t=>{
 const {connect,game}=await fixture(t,{reconnectMs:350}),teacher=await connect(),r=await create(teacher);
 const s=await connect(),j=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 teacher.disconnect();await sleep(80);const p=game.store.rooms.get(r.room.code).players.get(j.selfId),x=p.x;
 s.emit('player:input',{x:1,y:0});await sleep(120);assert.equal(p.x,x);
 await sleep(300);assert.equal(game.store.rooms.size,0);
});
test('HTTP serves only public assets; secrets and records never served',async t=>{
 const {url}=await fixture(t);
 for(const path of ['/.env','/server/app.js','/메인.md','/.local/teacher.html','/../.env'])
  assert.equal((await fetch(url+path)).status,404,path);
 const page=await fetch(url);assert.equal(page.status,200);assert.match(page.headers.get('content-security-policy'),/frame-ancestors 'none'/);
 assert.match(await page.text(),/사이버 교실/);
});
test('cross-origin websocket browser access is refused',async t=>{
 const {url}=await fixture(t);
 const s=io(url,{transports:['websocket'],reconnection:false,extraHeaders:{Origin:'https://untrusted.example'}});
 t.after(()=>s.disconnect());
 await new Promise((resolve,reject)=>{s.once('connect',()=>reject(new Error('origin accepted')));s.once('connect_error',resolve);});
});
test('chat messages reach only the same room, with nickname, role and flagged reported',async t=>{
 const {connect}=await fixture(t),teacherA=await connect(),teacherB=await connect();
 const ra=await create(teacherA),rb=await create(teacherB);
 const a1=await connect(),a2=await connect(),b1=await connect();
 const joinA1=await call(a1,'room:join',{code:ra.room.code,nickname:'1'});
 await call(a2,'room:join',{code:ra.room.code,nickname:'2'});
 await call(b1,'room:join',{code:rb.room.code,nickname:'1'});
 const seenTeacher=new Promise(resolve=>teacherA.once('chat:message',resolve));
 const seenA2=new Promise(resolve=>a2.once('chat:message',resolve));
 let leaked=false;b1.on('chat:message',()=>{leaked=true;});teacherB.on('chat:message',()=>{leaked=true;});
 assert.equal((await call(a1,'chat:send',{text:'안녕하세요!'})).ok,true);
 for(const m of await Promise.all([seenTeacher,seenA2])){
  assert.equal(m.nickname,'1');assert.equal(m.role,'student');assert.equal(m.text,'안녕하세요!');
  assert.equal(m.flagged,false);assert.equal(m.playerId,joinA1.selfId);
 }
 await sleep(60);assert.equal(leaked,false);
});
test('blocked words are masked before broadcasting',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const seen=new Promise(resolve=>teacher.once('chat:message',resolve));
 await call(s,'chat:send',{text:'너 진짜 병신 같다'});
 const m=await seen;assert.equal(m.flagged,true);assert.equal(m.text,'너 진짜 ○○ 같다');
});
test('chat text is validated before anything else, independent of cooldown',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 for(const text of ['','   ','a'.repeat(121),'hi'+String.fromCharCode(7)+'there','줄'+String.fromCharCode(10)+'바꿈',123]){
  const res=await call(s,'chat:send',{text});
  assert.equal(res.ok,false);assert.equal(res.error,'채팅은 1~120자로 입력해주세요.');
 }
});
test('chat cooldown rejects an immediate repeat send',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 assert.equal((await call(s,'chat:send',{text:'하나'})).ok,true);
 const second=await call(s,'chat:send',{text:'둘'});
 assert.equal(second.ok,false);assert.equal(second.error,'조금 천천히 말해요.');
});
test('teacher can turn chat off and on; students are blocked while off but the teacher is not',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const states=[];teacher.on('room:state',st=>states.push(st));
 const sysMsgs=[];s.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(s,'chat:setEnabled',{enabled:false})).error,'선생님만 할 수 있어요.');
 assert.equal((await call(teacher,'chat:setEnabled',{enabled:false})).ok,true);
 await sleep(30);assert.ok(states.some(st=>st.chat.enabled===false));
 const blocked=await call(s,'chat:send',{text:'안녕'});
 assert.equal(blocked.ok,false);assert.equal(blocked.error,'선생님이 채팅을 껐어요.');
 assert.equal((await call(teacher,'chat:send',{text:'선생님은 보낼 수 있어요'})).ok,true);
 assert.ok(sysMsgs.some(m=>m.role==='system'&&m.text==='선생님이 채팅을 껐어요.'));
 assert.equal((await call(teacher,'chat:setEnabled',{enabled:true})).ok,true);
 await sleep(30);assert.ok(states.some(st=>st.chat.enabled===true));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 채팅을 켰어요.'));
});
test('teacher can mute and unmute a student; only a teacher may manage chat and only a student can be muted',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 assert.equal((await call(s,'chat:mute',{playerId:joined.selfId,muted:true})).error,'선생님만 할 수 있어요.');
 assert.equal((await call(s,'chat:clear',{})).error,'선생님만 할 수 있어요.');
 const muteSelf=await call(teacher,'chat:mute',{playerId:r.selfId,muted:true});
 assert.equal(muteSelf.ok,false);assert.equal(muteSelf.error,'친구를 찾지 못했어요.');
 assert.equal((await call(teacher,'chat:mute',{playerId:joined.selfId,muted:true})).ok,true);
 assert.equal(game.store.rooms.get(r.room.code).players.get(joined.selfId).muted,true);
 const blocked=await call(s,'chat:send',{text:'안녕'});
 assert.equal(blocked.ok,false);assert.equal(blocked.error,'선생님이 내 채팅을 잠시 멈췄어요.');
 assert.equal((await call(teacher,'chat:mute',{playerId:joined.selfId,muted:false})).ok,true);
 assert.equal(game.store.rooms.get(r.room.code).players.get(joined.selfId).muted,false);
});
test('teacher clearing chat wipes broadcast history but leaves a system note for new joiners',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 await call(s,'chat:send',{text:'지워질 메시지'});
 const clearedEvent=new Promise(resolve=>teacher.once('chat:cleared',resolve));
 assert.equal((await call(teacher,'chat:clear',{})).ok,true);await clearedEvent;
 const newcomer=await connect();
 const joined=await call(newcomer,'room:join',{code:r.room.code,nickname:'2'});
 assert.ok(joined.chat.messages.every(m=>m.text!=='지워질 메시지'));
 assert.ok(joined.chat.messages.some(m=>m.role==='system'&&m.text==='선생님이 채팅 기록을 지웠어요.'));
});
test('a student can propose a new planet; invalid name/color/location are rejected, valid ones create a pending proposal',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 assert.equal((await call(teacher,'planet:propose',{name:'행성',description:'',x:190,y:175,color:PLANET_COLORS[0]})).error,
   '선생님은 행성 만들기로 바로 만들 수 있어요.');
 const tooShort=await call(s,'planet:propose',{name:'가',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 assert.equal(tooShort.ok,false);assert.equal(tooShort.error,'행성 이름은 2~10자(한글·영문·숫자)로 적어주세요.');
 const badWord=await call(s,'planet:propose',{name:'바보행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 assert.equal(badWord.ok,false);assert.equal(badWord.error,'행성 이름에 쓸 수 없는 말이 있어요.');
 const badColor=await call(s,'planet:propose',{name:'독서행성',description:'',x:190,y:175,color:'#000000'});
 assert.equal(badColor.ok,false);assert.equal(badColor.error,'행성 색을 골라주세요.');
 const overlap=await call(s,'planet:propose',{name:'독서행성',description:'',x:600,y:170,color:PLANET_COLORS[0]});
 assert.equal(overlap.ok,false);assert.equal(overlap.error,'그 자리에는 행성을 만들 수 없어요. 조금 떨어진 곳을 골라주세요.');
 const states=[];teacher.on('room:state',st=>states.push(st));
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const ok=await call(s,'planet:propose',{name:'독서행성',description:'책 읽기',x:190,y:175,color:PLANET_COLORS[0]});
 assert.equal(ok.ok,true);
 await sleep(30);
 assert.ok(states.some(st=>st.proposals.some(p=>p.id===ok.proposalId && p.name==='독서행성' && p.nickname==='1')));
 assert.ok(sysMsgs.some(m=>m.text==='1 친구가 새 행성 "독서행성"을 신청했어요. 선생님의 승인을 기다려요.'));
 const already=await call(s,'planet:propose',{name:'다른행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 assert.equal(already.ok,false);assert.equal(already.error,'이미 승인을 기다리는 행성이 있어요.');
});
test('pending-proposal limit blocks a further proposal once maxPending is reached',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const students=await Promise.all(Array.from({length:PLANET.maxPending+1},()=>connect()));
 await Promise.all(students.map((st,i)=>call(st,'room:join',{code:r.room.code,nickname:String(i+1)})));
 for(let i=0;i<PLANET.maxPending;i++){
  // y:550인 가로줄은 별(600,170)과 별빛 거리로 가는 문(1120,380) 둘 다에서 충분히 떨어져 있습니다.
  const res=await call(students[i],'planet:propose',{name:'행성'+i,description:'',x:100+i*200,y:550,color:PLANET_COLORS[i%PLANET_COLORS.length]});
  assert.equal(res.ok,true,'propose '+i+' failed: '+res.error);
 }
 const over=await call(students[PLANET.maxPending],'planet:propose',{name:'초과행성',description:'',x:100,y:600,color:PLANET_COLORS[0]});
 assert.equal(over.ok,false);assert.equal(over.error,'승인을 기다리는 행성이 너무 많아요. 잠시 후 다시 신청해주세요.');
});
test('the 12-per-room planet limit blocks further teacher creation and student proposals',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const room=game.store.rooms.get(r.room.code);
 let created=0,colorIndex=0;
 outer: for(let y=100;y<720;y+=160)
  for(let x=100;x<1150;x+=200){
   if(created>=PLANET.maxPerRoom) break outer;
   if(!placementFree(room,x,y)) continue;
   const res=await call(teacher,'planet:create',{name:'행성'+created,description:'',x,y,color:PLANET_COLORS[colorIndex%PLANET_COLORS.length]});
   assert.equal(res.ok,true,'create '+created+' failed: '+res.error);
   colorIndex++;created++;
  }
 assert.equal(created,PLANET.maxPerRoom);
 const overLimitCreate=await call(teacher,'planet:create',{name:'초과행성',description:'',x:600,y:400,color:PLANET_COLORS[0]});
 assert.equal(overLimitCreate.ok,false);assert.equal(overLimitCreate.error,'행성이 너무 많아요. (최대 '+PLANET.maxPerRoom+'개)');
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const overLimitPropose=await call(s,'planet:propose',{name:'초과행성2',description:'',x:600,y:400,color:PLANET_COLORS[0]});
 assert.equal(overLimitPropose.ok,false);assert.equal(overLimitPropose.error,'행성이 너무 많아요. (최대 '+PLANET.maxPerRoom+'개)');
});
test('teacher approves a proposal: it becomes a planet and the proposer becomes its first member, with announce',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const states=[];teacher.on('room:state',st=>states.push(st));
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const proposed=await call(s,'planet:propose',{name:'독서행성',description:'책 읽기',x:190,y:175,color:PLANET_COLORS[0]});
 assert.equal(proposed.ok,true);
 assert.equal((await call(s,'planet:approve',{proposalId:proposed.proposalId})).error,'선생님만 할 수 있어요.');
 assert.equal((await call(teacher,'planet:approve',{proposalId:'nope'})).error,'신청을 찾지 못했어요.');
 const approved=await call(teacher,'planet:approve',{proposalId:proposed.proposalId});
 assert.equal(approved.ok,true);
 await sleep(30);
 assert.ok(states.some(st=>st.planets.some(pl=>pl.id===approved.planetId && pl.name==='독서행성' && pl.memberCount===1) && st.proposals.length===0));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "독서행성" 행성을 승인했어요! 1 친구가 첫 멤버가 되었어요.'));
 const player=[...game.store.rooms.get(r.room.code).players.values()].find(pl=>pl.nickname==='1');
 assert.equal(player.avatar.departmentId,approved.planetId);
});
test('teacher can reject a proposal; a student can withdraw only their own',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s1=await connect(),s2=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const p1=await call(s1,'planet:propose',{name:'일기행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 assert.equal(p1.ok,true);
 assert.equal((await call(s2,'planet:withdraw',{proposalId:p1.proposalId})).error,'내 신청만 취소할 수 있어요.');
 assert.equal((await call(s1,'planet:withdraw',{proposalId:'nope'})).error,'신청을 찾지 못했어요.');
 const withdrawn=await call(s1,'planet:withdraw',{proposalId:p1.proposalId});
 assert.equal(withdrawn.ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='1 친구가 "일기행성" 행성 신청을 취소했어요.'));
 const p2=await call(s2,'planet:propose',{name:'청소행성',description:'',x:190,y:565,color:PLANET_COLORS[2]});
 assert.equal(p2.ok,true);
 assert.equal((await call(s1,'planet:reject',{proposalId:p2.proposalId})).error,'선생님만 할 수 있어요.');
 const rejected=await call(teacher,'planet:reject',{proposalId:p2.proposalId});
 assert.equal(rejected.ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "청소행성" 행성 신청을 돌려보냈어요.'));
});
test('creating a planet on top of a standing plaza player pushes them out',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 p.x=500;p.y=500;p.mapId=PLAZA_ID;
 const created=await call(teacher,'planet:create',{name:'교과행성',description:'',x:500,y:500,color:PLANET_COLORS[3]});
 assert.equal(created.ok,true);
 assert.ok(Math.hypot(p.x-500,p.y-500) >= PLANET.radius+RULES.radius);
});
test('teacher can remove a planet: interior occupants return to the plaza and membership is cleared',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 await call(s,'planet:join',{planetId:created.planetId});
 p.x=190;p.y=175+60;
 await call(s,'planet:enter',{planetId:created.planetId});
 assert.equal(p.mapId,interiorIdOf(created.planetId));
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(s,'planet:remove',{planetId:created.planetId})).error,'선생님만 할 수 있어요.');
 const removed=await call(teacher,'planet:remove',{planetId:created.planetId});
 assert.equal(removed.ok,true);
 assert.equal(p.mapId,PLAZA_ID);
 assert.equal(p.avatar.departmentId,null);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "독서행성" 행성을 없앴어요.'));
 assert.equal((await call(teacher,'planet:remove',{planetId:created.planetId})).error,'행성을 찾지 못했어요.');
});
test('students join and transfer planets; teachers cannot join and re-joining the same planet is rejected',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const reading=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const diary=await call(teacher,'planet:create',{name:'일기행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const states=[];teacher.on('room:state',st=>states.push(st));
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(teacher,'planet:join',{planetId:reading.planetId})).error,'선생님은 모든 행성에 들어갈 수 있어요.');
 assert.equal((await call(s,'planet:join',{planetId:reading.planetId})).ok,true);
 await sleep(30);
 assert.ok(states.some(st=>st.players.some(p=>p.nickname==='1'&&p.departmentId===reading.planetId)));
 assert.ok(sysMsgs.some(m=>m.text==='1 친구가 독서행성에 가입했어요.'));
 const again=await call(s,'planet:join',{planetId:reading.planetId});
 assert.equal(again.ok,false);assert.equal(again.error,'이미 독서행성 소속이에요.');
 const moved=await call(s,'planet:join',{planetId:diary.planetId});
 assert.equal(moved.ok,true);
 await sleep(30);
 assert.ok(states.some(st=>st.players.some(p=>p.nickname==='1'&&p.departmentId===diary.planetId)));
 assert.ok(sysMsgs.some(m=>m.text==='1 친구가 독서행성에서 일기행성으로 옮겼어요.'));
});
test('entering a planet requires membership (or teacher) and proximity; success moves the player inside',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const reading=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const rejectNotMember=await call(s,'planet:enter',{planetId:reading.planetId});
 assert.equal(rejectNotMember.ok,false);assert.equal(rejectNotMember.error,'독서행성 소속 친구만 들어갈 수 있어요.');
 assert.equal((await call(s,'planet:join',{planetId:reading.planetId})).ok,true);
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 p.x=190+1000;p.y=175+1000;
 const tooFar=await call(s,'planet:enter',{planetId:reading.planetId});
 assert.equal(tooFar.ok,false);assert.equal(tooFar.error,'행성에 더 가까이 가주세요.');
 p.x=190;p.y=175+PLANET.radius;
 const entered=await call(s,'planet:enter',{planetId:reading.planetId});
 assert.equal(entered.ok,true);
 assert.equal(p.mapId,interiorIdOf(reading.planetId));
 assert.ok(Math.hypot(p.x-600,p.y-560)<400);
 const tp=game.store.rooms.get(r.room.code).players.get(r.selfId);
 tp.x=190;tp.y=175+PLANET.radius;
 const teacherEnter=await call(teacher,'planet:enter',{planetId:reading.planetId});
 assert.equal(teacherEnter.ok,true);
 assert.equal(tp.mapId,interiorIdOf(reading.planetId));
});
test('planet:join is rejected while inside a planet; exiting returns to the plaza just below it; exit is rejected from the plaza',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const reading=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const diary=await call(teacher,'planet:create',{name:'일기행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 assert.equal((await call(s,'planet:exit',{})).error,'지금은 광장에 있어요.');
 await call(s,'planet:join',{planetId:reading.planetId});
 p.x=190;p.y=175+PLANET.radius;
 await call(s,'planet:enter',{planetId:reading.planetId});
 for(const planetId of [reading.planetId,diary.planetId]){
  const rejected=await call(s,'planet:join',{planetId});
  assert.equal(rejected.ok,false);
  assert.equal(rejected.error,'광장에서만 행성에 가입할 수 있어요.');
 }
 const exited=await call(s,'planet:exit',{});
 assert.equal(exited.ok,true);
 assert.equal(p.mapId,PLAZA_ID);
 assert.ok(p.y>175+PLANET.radius);
 assert.ok(Math.abs(p.x-190)<100);
});
test('a student inside a planet can leave, returning to the plaza with membership cleared',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const reading=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 await call(s,'planet:join',{planetId:reading.planetId});
 p.x=190;p.y=175+PLANET.radius;
 await call(s,'planet:enter',{planetId:reading.planetId});
 assert.equal(p.mapId,interiorIdOf(reading.planetId));
 const left=await call(s,'planet:leave',{planetId:reading.planetId});
 assert.equal(left.ok,true);
 assert.equal(p.mapId,PLAZA_ID);
 assert.equal(p.avatar.departmentId,null);
});
test('only the teacher can set a planet rules; valid rules broadcast and announce, invalid ones are rejected',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const reading=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const states=[];teacher.on('room:state',st=>states.push(st));
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(s,'planet:rules:set',{planetId:reading.planetId,rules:['안전 규칙']})).error,'선생님만 할 수 있어요.');
 const newRules=['첫째 줄','둘째 줄'];
 const ok=await call(teacher,'planet:rules:set',{planetId:reading.planetId,rules:newRules});
 assert.equal(ok.ok,true);
 await sleep(30);
 assert.ok(states.some(st=>JSON.stringify(st.planets.find(pl=>pl.id===reading.planetId).rules)===JSON.stringify(newRules)));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 독서행성의 규칙을 바꿨어요.'));
 const tooMany=await call(teacher,'planet:rules:set',{planetId:reading.planetId,rules:Array.from({length:9},(_,i)=>'줄'+i)});
 assert.equal(tooMany.ok,false);assert.equal(tooMany.error,'규칙은 1~8줄, 한 줄 40자 이내로 적어주세요.');
 const tooLong=await call(teacher,'planet:rules:set',{planetId:reading.planetId,rules:['a'.repeat(41)]});
 assert.equal(tooLong.ok,false);
 const control=await call(teacher,'planet:rules:set',{planetId:reading.planetId,rules:['줄'+String.fromCharCode(7)+'바꿈']});
 assert.equal(control.ok,false);
 const empty=await call(teacher,'planet:rules:set',{planetId:reading.planetId,rules:[]});
 assert.equal(empty.ok,false);
});
test('rename vote passes immediately with a single member',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 await call(s,'planet:join',{planetId:created.planetId});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const proposed=await call(s,'planet:rename:propose',{planetId:created.planetId,name:'책읽기행성'});
 assert.equal(proposed.ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='"독서행성" 행성 친구들이 이름을 "책읽기행성"으로 바꿀지 투표를 시작했어요.'));
 assert.ok(sysMsgs.some(m=>m.text==='"독서행성" 행성의 이름이 "책읽기행성"으로 바뀌었어요!'));
 const planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'책읽기행성');assert.equal(planet.rename,null);
});
test('rename announcements pick the Korean particle 로/으로 from the new name ending',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'교과행성',description:'',x:1010,y:565,color:PLANET_COLORS[3]});
 const s=await connect();await call(s,'room:join',{code:r.room.code,nickname:'1'});
 await call(s,'planet:join',{planetId:created.planetId});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 // 받침 없이 끝나는 이름은 '로', ㄹ 받침도 '로', 그 밖의 받침은 '으로'가 붙어야 합니다.
 assert.equal((await call(s,'planet:rename:propose',{planetId:created.planetId,name:'급식나라'})).ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='"교과행성" 행성 친구들이 이름을 "급식나라"로 바꿀지 투표를 시작했어요.'));
 assert.ok(sysMsgs.some(m=>m.text==='"교과행성" 행성의 이름이 "급식나라"로 바뀌었어요!'));
 assert.equal((await call(teacher,'planet:rename:set',{planetId:created.planetId,name:'급식별'})).ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "급식나라" 행성의 이름을 "급식별"로 바꿨어요.'));
 assert.equal((await call(teacher,'planet:rename:set',{planetId:created.planetId,name:'급식행성'})).ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "급식별" 행성의 이름을 "급식행성"으로 바꿨어요.'));
});
test('rename vote is rejected when a second member votes no (2 members)',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'일기행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 const s1=await connect(),s2=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(s1,'planet:join',{planetId:created.planetId});
 await call(s2,'planet:join',{planetId:created.planetId});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const proposed=await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'기록행성'});
 assert.equal(proposed.ok,true);
 assert.equal((await call(teacher,'planet:rename:vote',{planetId:created.planetId,agree:false})).error,'일기행성 소속 친구만 투표할 수 있어요.');
 const voted=await call(s2,'planet:rename:vote',{planetId:created.planetId,agree:false});
 assert.equal(voted.ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='"기록행성" 이름 바꾸기가 부결되었어요.'));
 const planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'일기행성');assert.equal(planet.rename,null);
});
test('rename vote passes once 2 of 3 members agree, without waiting for the third',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'청소행성',description:'',x:190,y:565,color:PLANET_COLORS[2]});
 const s1=await connect(),s2=await connect(),s3=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(s3,'room:join',{code:r.room.code,nickname:'3'});
 for(const s of [s1,s2,s3]) await call(s,'planet:join',{planetId:created.planetId});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'청소행성'})).error,'지금 이름과 같아요.');
 const proposed=await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'청결행성'});
 assert.equal(proposed.ok,true);
 assert.equal((await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'또다른'})).error,'이미 이름 바꾸기 투표가 진행 중이에요.');
 const voted=await call(s2,'planet:rename:vote',{planetId:created.planetId,agree:true});
 assert.equal(voted.ok,true);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='"청소행성" 행성의 이름이 "청결행성"으로 바뀌었어요!'));
 const planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'청결행성');
 assert.equal((await call(s3,'planet:rename:vote',{planetId:created.planetId,agree:true})).error,'진행 중인 투표가 없어요.');
});
test('a non-member cannot vote on a planet rename',async t=>{
 const {connect}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'교과행성',description:'',x:1010,y:565,color:PLANET_COLORS[3]});
 const s1=await connect(),s2=await connect(),outsider=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(outsider,'room:join',{code:r.room.code,nickname:'3'});
 await call(s1,'planet:join',{planetId:created.planetId});
 await call(s2,'planet:join',{planetId:created.planetId});
 // 멤버가 2명이라 제안자 혼자 찬성한 상태로는 즉시 통과하지 않고 투표가 진행 중으로 남습니다.
 await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'수업행성'});
 const rejected=await call(outsider,'planet:rename:vote',{planetId:created.planetId,agree:true});
 assert.equal(rejected.ok,false);assert.equal(rejected.error,'교과행성 소속 친구만 투표할 수 있어요.');
});
test('rename re-evaluates when membership shrinks (a member leaving the planet can flip a pending vote to pass)',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s1=await connect(),s2=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(s1,'planet:join',{planetId:created.planetId});
 await call(s2,'planet:join',{planetId:created.planetId});
 const proposed=await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'책읽기행성'});
 assert.equal(proposed.ok,true);
 let planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.ok(planet.rename);
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const left=await call(s2,'planet:leave',{planetId:created.planetId});
 assert.equal(left.ok,true);
 await sleep(20);
 planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'책읽기행성');assert.equal(planet.rename,null);
 assert.ok(sysMsgs.some(m=>m.text==='"독서행성" 행성의 이름이 "책읽기행성"으로 바뀌었어요!'));
});
test('a member leaving the classroom entirely also re-evaluates a pending rename vote',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s1=await connect(),s2=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(s1,'planet:join',{planetId:created.planetId});
 await call(s2,'planet:join',{planetId:created.planetId});
 await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'책읽기행성'});
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.ok((await call(s2,'room:leave')).ok);
 await sleep(20);
 const planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'책읽기행성');assert.equal(planet.rename,null);
 assert.ok(sysMsgs.some(m=>m.text==='"독서행성" 행성의 이름이 "책읽기행성"으로 바뀌었어요!'));
});
test('teacher can rename a planet directly, clearing any pending vote',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'일기행성',description:'',x:1010,y:175,color:PLANET_COLORS[1]});
 const s1=await connect(),s2=await connect();
 await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 await call(s1,'planet:join',{planetId:created.planetId});
 await call(s2,'planet:join',{planetId:created.planetId});
 await call(s1,'planet:rename:propose',{planetId:created.planetId,name:'기록행성'});
 assert.equal((await call(s1,'planet:rename:set',{planetId:created.planetId,name:'새이름'})).error,'선생님만 할 수 있어요.');
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 const set=await call(teacher,'planet:rename:set',{planetId:created.planetId,name:'새이름'});
 assert.equal(set.ok,true);
 await sleep(20);
 const planet=game.store.rooms.get(r.room.code).planets.get(created.planetId);
 assert.equal(planet.name,'새이름');assert.equal(planet.rename,null);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 "일기행성" 행성의 이름을 "새이름"으로 바꿨어요.'));
 assert.equal((await call(teacher,'planet:rename:set',{planetId:created.planetId,name:'새이름'})).error,'지금 이름과 같아요.');
});
test('planet system messages do not leak to another classroom',async t=>{
 const {connect}=await fixture(t),teacherA=await connect(),teacherB=await connect();
 const ra=await create(teacherA),rb=await create(teacherB);
 const a1=await connect(),b1=await connect();
 await call(a1,'room:join',{code:ra.room.code,nickname:'1'});
 await call(b1,'room:join',{code:rb.room.code,nickname:'1'});
 let leaked=false;teacherB.on('chat:message',()=>{leaked=true;});b1.on('chat:message',()=>{leaked=true;});
 const proposed=await call(a1,'planet:propose',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 assert.equal(proposed.ok,true);
 assert.equal((await call(teacherA,'planet:approve',{proposalId:proposed.proposalId})).ok,true);
 await sleep(60);
 assert.equal(leaked,false);
});
test('resume preserves the player mapId and department after reconnecting',async t=>{
 const {connect,game}=await fixture(t,{reconnectMs:500}),teacher=await connect(),r=await create(teacher);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 await call(s,'planet:join',{planetId:created.planetId});
 p.x=190;p.y=175+PLANET.radius;
 await call(s,'planet:enter',{planetId:created.planetId});
 assert.equal(p.mapId,interiorIdOf(created.planetId));
 s.disconnect();await sleep(60);
 const resumed=await connect();
 const result=await call(resumed,'session:resume',{token:joined.token});
 assert.ok(result.ok);
 assert.equal(p.mapId,interiorIdOf(created.planetId));
 assert.equal(p.avatar.departmentId,created.planetId);
 const rp=result.room.players.find(x=>x.id===joined.selfId);
 assert.equal(rp.mapId,interiorIdOf(created.planetId));
 assert.equal(rp.departmentId,created.planetId);
});
test('resume includes recent chat history, trimmed to the configured size from the oldest end',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 await call(s,'chat:send',{text:'재접속 전 인사'});
 s.disconnect();await sleep(60);
 const resumedSocket=await connect();
 const result=await call(resumedSocket,'session:resume',{token:joined.token});
 assert.ok(result.ok);assert.ok(result.chat.messages.some(m=>m.text==='재접속 전 인사'));
 const room=game.store.rooms.get(r.room.code);
 for(let i=0;i<60;i++) game.store.pushChat(room,{playerId:null,nickname:'안내',role:'system',text:'채움'+i,flagged:false});
 assert.equal(room.chat.history.length,50);
 resumedSocket.disconnect();await sleep(60);
 const resumedAgain=await connect();
 const result2=await call(resumedAgain,'session:resume',{token:joined.token});
 assert.equal(result2.chat.messages.length,50);
 assert.equal(result2.chat.messages[0].text,'채움10');
 assert.equal(result2.chat.messages[49].text,'채움59');
});
test('map:travel requires a nearby gate to a real map; success moves the player to the arrival point',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 const invalidTo=await call(s,'map:travel',{to:'nowhere'});
 assert.equal(invalidTo.ok,false);assert.equal(invalidTo.error,'그런 곳은 없어요.');
 const tooFar=await call(s,'map:travel',{to:STREET_ID});
 assert.equal(tooFar.ok,false);assert.equal(tooFar.error,'문에 더 가까이 가주세요.');
 const gate=MAP.objects.find(o=>o.kind==='gate');
 p.x=gate.x;p.y=gate.y;
 const travelled=await call(s,'map:travel',{to:STREET_ID});
 assert.equal(travelled.ok,true);
 assert.equal(p.mapId,STREET_ID);
 assert.ok(Math.hypot(p.x-gate.arrival.x,p.y-gate.arrival.y)<400);
 const streetGate=STREET.objects.find(o=>o.kind==='gate');
 const stillFar=await call(s,'map:travel',{to:PLAZA_ID});
 assert.equal(stillFar.ok,false);assert.equal(stillFar.error,'문에 더 가까이 가주세요.');
 p.x=streetGate.x;p.y=streetGate.y;
 const back=await call(s,'map:travel',{to:PLAZA_ID});
 assert.equal(back.ok,true);assert.equal(p.mapId,PLAZA_ID);
 const created=await call(teacher,'planet:create',{name:'독서행성',description:'',x:190,y:175,color:PLANET_COLORS[0]});
 await call(s,'planet:join',{planetId:created.planetId});
 p.x=190;p.y=175+PLANET.radius;
 await call(s,'planet:enter',{planetId:created.planetId});
 const insideTravel=await call(s,'map:travel',{to:STREET_ID});
 assert.equal(insideTravel.ok,false);assert.equal(insideTravel.error,'여기서는 그곳으로 갈 수 없어요.');
});
test('teacher gives or takes star shards from one student or everyone; amounts are validated and clamped',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s1=await connect(),s2=await connect();
 const j1=await call(s1,'room:join',{code:r.room.code,nickname:'1'});
 const j2=await call(s2,'room:join',{code:r.room.code,nickname:'2'});
 const p1=game.store.rooms.get(r.room.code).players.get(j1.selfId);
 const p2=game.store.rooms.get(r.room.code).players.get(j2.selfId);
 assert.equal((await call(s1,'shards:give',{playerId:j1.selfId,amount:10})).error,'선생님만 할 수 있어요.');
 for(const amount of [0,1000,1.5,-1000])
  assert.equal((await call(teacher,'shards:give',{playerId:j1.selfId,amount})).error,'별 파편 개수는 1~999 사이 정수로 적어주세요.');
 assert.equal((await call(teacher,'shards:give',{playerId:'nope',amount:5})).error,'친구를 찾지 못했어요.');
 const sysMsgs=[];teacher.on('chat:message',m=>sysMsgs.push(m));
 assert.equal((await call(teacher,'shards:give',{playerId:j1.selfId,amount:10})).ok,true);
 assert.equal(p1.starShards,10);
 assert.equal((await call(teacher,'shards:give',{playerId:j1.selfId,amount:-3})).ok,true);
 assert.equal(p1.starShards,7);
 assert.equal((await call(teacher,'shards:give',{playerId:j1.selfId,amount:-100})).ok,true);
 assert.equal(p1.starShards,0);
 p1.starShards=SHARDS.max-5;
 assert.equal((await call(teacher,'shards:give',{playerId:j1.selfId,amount:SHARDS.giveMax})).ok,true);
 assert.equal(p1.starShards,SHARDS.max);
 assert.equal((await call(teacher,'shards:give',{playerId:'all',amount:5})).ok,true);
 assert.equal(p2.starShards,5);
 assert.equal((await call(teacher,'shards:give',{playerId:'all',amount:-2})).ok,true);
 assert.equal(p2.starShards,3);
 await sleep(20);
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 1 친구에게 별 파편 10개를 주었어요.'));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 1 친구의 별 파편 3개를 거두었어요.'));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 모두에게 별 파편 5개씩 주었어요.'));
 assert.ok(sysMsgs.some(m=>m.text==='선생님이 모두의 별 파편 2개씩 거두었어요.'));
});
test('star shards and star-street purchases stay isolated per classroom',async t=>{
 const {connect,game}=await fixture(t),teacherA=await connect(),teacherB=await connect();
 const ra=await create(teacherA),rb=await create(teacherB);
 const a1=await connect(),b1=await connect();
 const ja=await call(a1,'room:join',{code:ra.room.code,nickname:'1'});
 const jb=await call(b1,'room:join',{code:rb.room.code,nickname:'1'});
 assert.equal((await call(teacherA,'shards:give',{playerId:ja.selfId,amount:20})).ok,true);
 const pa=game.store.rooms.get(ra.room.code).players.get(ja.selfId);
 const pb=game.store.rooms.get(rb.room.code).players.get(jb.selfId);
 assert.equal(pa.starShards,20);assert.equal(pb.starShards,0);
 assert.equal((await call(teacherB,'shards:give',{playerId:ja.selfId,amount:5})).error,'친구를 찾지 못했어요.');
});
test('star shop enforces location, funds, stack and bag limits; buying and selling update shards and inventory together',async t=>{
 const {connect,game}=await fixture(t),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 const item=SHOP.items[0];
 const fromPlaza=await call(s,'shop:buy',{itemId:item.id,quantity:1});
 assert.equal(fromPlaza.ok,false);assert.equal(fromPlaza.error,'별상점은 별빛 거리에 있어요.');
 const gate=MAP.objects.find(o=>o.kind==='gate');
 p.x=gate.x;p.y=gate.y;
 assert.equal((await call(s,'map:travel',{to:STREET_ID})).ok,true);
 const farBuy=await call(s,'shop:buy',{itemId:item.id,quantity:1});
 assert.equal(farBuy.ok,false);assert.equal(farBuy.error,'별상점에 더 가까이 가주세요.');
 const shop=STREET.objects.find(o=>o.kind==='shop');
 p.x=shop.x;p.y=shop.y;
 const noFunds=await call(s,'shop:buy',{itemId:item.id,quantity:1});
 assert.equal(noFunds.ok,false);assert.equal(noFunds.error,'별 파편이 부족해요. (필요 '+item.price+'개, 지금 0개)');
 assert.equal((await call(teacher,'shards:give',{playerId:joined.selfId,amount:100})).ok,true);
 const bought=await call(s,'shop:buy',{itemId:item.id,quantity:2});
 assert.equal(bought.ok,true);
 assert.equal(bought.starShards,100-item.price*2);
 assert.equal(p.starShards,bought.starShards);
 assert.deepEqual(bought.inventory,[{id:item.id,quantity:2}]);
 assert.deepEqual(p.inventory,[{id:item.id,quantity:2}]);
 const badItem=await call(s,'shop:buy',{itemId:'nope',quantity:1});
 assert.equal(badItem.ok,false);assert.equal(badItem.error,'그런 물건은 없어요.');
 for(const quantity of [0,11]){
  const res=await call(s,'shop:buy',{itemId:item.id,quantity});
  assert.equal(res.ok,false);assert.equal(res.error,'1~10개씩 사고팔 수 있어요.');
 }
 p.starShards=SHARDS.max;
 p.inventory=[{id:item.id,quantity:95}];
 const overStack=await call(s,'shop:buy',{itemId:item.id,quantity:5});
 assert.equal(overStack.ok,false);assert.equal(overStack.error,'한 종류는 99개까지만 가질 수 있어요.');
 const otherItem=SHOP.items[1];
 p.inventory=SHOP.items.filter(it=>it.id!==otherItem.id).map(it=>({id:it.id,quantity:1}))
   .concat(Array.from({length:30-(SHOP.items.length-1)},(_,i)=>({id:'filler'+i,quantity:1})));
 assert.equal(p.inventory.length,30);
 const fullBag=await call(s,'shop:buy',{itemId:otherItem.id,quantity:1});
 assert.equal(fullBag.ok,false);assert.equal(fullBag.error,'가방이 가득 찼어요.');
 p.inventory=[{id:item.id,quantity:4}];p.starShards=0;
 const sellTooMany=await call(s,'shop:sell',{itemId:item.id,quantity:5});
 assert.equal(sellTooMany.ok,false);assert.equal(sellTooMany.error,'그만큼 가지고 있지 않아요.');
 const sold=await call(s,'shop:sell',{itemId:item.id,quantity:4});
 assert.equal(sold.ok,true);
 assert.equal(sold.starShards,Math.floor(item.price*SHOP.sellRate)*4);
 assert.equal(p.starShards,sold.starShards);
 assert.deepEqual(sold.inventory,[]);
 assert.deepEqual(p.inventory,[]);
});
test('resume after reconnecting keeps star shards, inventory and the star-street map',async t=>{
 const {connect,game}=await fixture(t,{reconnectMs:500}),teacher=await connect(),r=await create(teacher);
 const s=await connect(),joined=await call(s,'room:join',{code:r.room.code,nickname:'1'});
 const p=game.store.rooms.get(r.room.code).players.get(joined.selfId);
 const gate=MAP.objects.find(o=>o.kind==='gate');
 p.x=gate.x;p.y=gate.y;
 assert.equal((await call(s,'map:travel',{to:STREET_ID})).ok,true);
 assert.equal((await call(teacher,'shards:give',{playerId:joined.selfId,amount:30})).ok,true);
 const shop=STREET.objects.find(o=>o.kind==='shop');
 p.x=shop.x;p.y=shop.y;
 const item=SHOP.items[0];
 assert.equal((await call(s,'shop:buy',{itemId:item.id,quantity:1})).ok,true);
 s.disconnect();await sleep(60);
 const resumed=await connect();
 const result=await call(resumed,'session:resume',{token:joined.token});
 assert.ok(result.ok);
 assert.equal(p.mapId,STREET_ID);
 assert.equal(p.starShards,30-item.price);
 assert.deepEqual(p.inventory,[{id:item.id,quantity:1}]);
 const rp=result.room.players.find(x=>x.id===joined.selfId);
 assert.equal(rp.mapId,STREET_ID);
 assert.equal(rp.starShards,30-item.price);
 assert.deepEqual(rp.inventory,[{id:item.id,quantity:1}]);
});
