import test from 'node:test';
import assert from 'node:assert/strict';
import {io} from 'socket.io-client';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createClassroomServer} from '../server/app.js';
import {MAP,PLAZA_ID} from '../shared/config.js';

test('선생님이 체크한 알림장 줄만 학생 과제로 가져와 완료하고 안드로메다 명단에 이름순으로 남긴다',async t=>{
  const game=createClassroomServer({teacherKey:'assignment-test-private-key',studentHours:false});
  const address=await game.listen(),sockets=[];
  const connect=async()=>{const socket=io('http://127.0.0.1:'+address.port,{transports:['websocket'],reconnection:false});sockets.push(socket);await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();});
  const call=(socket,event,data={})=>socket.timeout(2500).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:'assignment-test-private-key',allowedNames:['다희','가은']});
  const first=await connect(),joinedFirst=await call(first,'room:join',{code:created.room.code,nickname:'다희'});
  const second=await connect(),joinedSecond=await call(second,'room:join',{code:created.room.code,nickname:'가은'});
  const room=game.store.rooms.get(created.room.code),teacherPlayer=room.players.get(created.selfId),a=room.players.get(joinedFirst.selfId),b=room.players.get(joinedSecond.selfId);
  const notice=MAP.objects.find(o=>o.id==='pillar-notice'),portal=MAP.objects.find(o=>o.kind==='andromeda');
  for(const player of [teacherPlayer,a,b])Object.assign(player,{mapId:PLAZA_ID,x:notice.x+65,y:notice.y});
  assert.equal((await call(first,'temple:save',{objectId:'pillar-notice',text:'물병 준비\n책 읽기',taskLineIndexes:[1]})).ok,false);
  const saved=await call(teacher,'temple:save',{objectId:'pillar-notice',text:'물병 준비\n책 읽기',taskLineIndexes:[1]});
  assert.equal(saved.taskLines.length,1);assert.equal(saved.taskLines[0].lineIndex,1);
  const assignmentId=saved.taskLines[0].assignmentId;
  assert.equal((await call(first,'task:add',{lineIndex:0,assignmentId})).ok,false);
  assert.equal((await call(first,'task:add',{lineIndex:1,assignmentId})).tasks.length,1);
  assert.equal((await call(first,'task:add',{lineIndex:1,assignmentId})).ok,false);
  assert.equal((await call(second,'task:add',{lineIndex:1,assignmentId})).tasks.length,1);
  assert.equal(room.players.get(a.id).tasks.length,1);
  const own=game.store.snapshot(room,a),other=game.store.snapshot(room,b);
  assert.equal(own.players.find(p=>p.id===a.id).tasks.length,1);
  assert.equal(other.players.find(p=>p.id===a.id).tasks,undefined);
  const aTask=a.tasks[0].id,bTask=b.tasks[0].id;
  assert.equal((await call(first,'task:complete',{taskId:aTask})).tasks.length,0);
  assert.equal((await call(second,'task:complete',{taskId:bTask})).tasks.length,0);
  assert.equal((await call(first,'task:complete',{taskId:aTask})).ok,false);
  Object.assign(teacherPlayer,{x:portal.x+260,y:portal.y});
  const gallery=await call(teacher,'assignment:read',{});
  assert.equal(gallery.weeks.length,3);assert.equal(gallery.weeks[0].assignments.length,1);
  assert.deepEqual(gallery.weeks[0].assignments[0].completed,['가은','다희']);
  Object.assign(b,{x:1100,y:1100});assert.equal((await call(second,'assignment:read',{})).ok,false);
  Object.assign(teacherPlayer,{x:notice.x+65,y:notice.y});
  const changed=await call(teacher,'temple:save',{objectId:'pillar-notice',text:'물병 준비\n다른 책 읽기',taskLineIndexes:[1]});
  assert.notEqual(changed.taskLines[0].assignmentId,assignmentId);
  assert.equal((await call(first,'task:add',{lineIndex:1,assignmentId})).ok,false);
});

test('개인 과제와 완료 명단은 서버 재시작 뒤에도 보존된다',async t=>{
  const directory=await mkdtemp(join(tmpdir(),'homework-save-')),key='homework-persistence-private-key',sockets=[];
  let game=createClassroomServer({teacherKey:key,dataDir:directory,studentHours:false}),address=await game.listen();
  t.after(async()=>{for(const socket of sockets)socket.disconnect();await game.close();await rm(directory,{recursive:true,force:true});});
  const connect=async()=>{const socket=io('http://127.0.0.1:'+address.port,{transports:['websocket'],reconnection:false});sockets.push(socket);await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
  const call=(socket,event,data={})=>socket.timeout(2500).emitWithAck(event,data);
  const teacher=await connect(),created=await call(teacher,'room:create',{teacherKey:key,allowedNames:['가람']});
  const pin=created.credentials[0].pin,student=await connect(),joined=await call(student,'room:join',{code:created.room.code,nickname:'가람',pin});
  let room=game.store.rooms.get(created.room.code),teacherPlayer=room.players.get(created.selfId),studentPlayer=room.players.get(joined.selfId);
  const notice=MAP.objects.find(o=>o.id==='pillar-notice');
  for(const p of [teacherPlayer,studentPlayer])Object.assign(p,{mapId:PLAZA_ID,x:notice.x+65,y:notice.y});
  const noticeSaved=await call(teacher,'temple:save',{objectId:'pillar-notice',text:'별 관찰',taskLineIndexes:[0]});
  assert.equal(noticeSaved.ok,true);
  assert.equal((await call(student,'task:add',{lineIndex:0,assignmentId:noticeSaved.taskLines[0].assignmentId})).tasks.length,1);
  for(const socket of sockets)socket.disconnect();await game.close();
  game=createClassroomServer({teacherKey:key,dataDir:directory,studentHours:false});address=await game.listen();
  const returned=await connect(),resumed=await call(returned,'room:join',{code:created.room.code,nickname:'가람',pin});
  room=game.store.rooms.get(created.room.code);studentPlayer=room.players.get(joined.selfId);
  assert.equal(resumed.selfId,joined.selfId);assert.equal(studentPlayer.tasks.length,1);
  assert.equal((await call(returned,'task:complete',{taskId:studentPlayer.tasks[0].id})).tasks.length,0);
  for(const socket of sockets)socket.disconnect();await game.close();
  game=createClassroomServer({teacherKey:key,dataDir:directory,studentHours:false});address=await game.listen();
  const reopened=await connect();assert.equal((await call(reopened,'room:open',{teacherKey:key,code:created.room.code})).ok,true);
  room=game.store.rooms.get(created.room.code);assert.equal(room.players.get(joined.selfId).tasks.length,0);
  const portal=MAP.objects.find(o=>o.kind==='andromeda'),newTeacher=[...room.players.values()].find(p=>p.role==='teacher');
  Object.assign(newTeacher,{mapId:PLAZA_ID,x:portal.x+260,y:portal.y});
  assert.deepEqual((await call(reopened,'assignment:read',{})).weeks[0].assignments[0].completed,['가람']);
});
